### ISSUE TITLE
documentation not up-to-date

### ISSUE THREAD

**Issue by Yanrich** [pivotal-cf/docs-scheduler#19]
The docs says that the latest release is  v1.2.3
https://docs.pivotal.io/pcf-scheduler/1-2/index.html#snapshot

On pivotal network, we have v1.2.5
https://network.pivotal.io/products/p-scheduler/#/releases/221276

Could you please update the documentation page?
Thank you

**Comment by mlimonczenko** [comment]
Hello @Yanrich,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
