### ISSUE TITLE
Support for PAS 2.4 and 2.5

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-scheduler#20]
The document for PCF Scheduler mentions only PAS 2.3 as the last supported version. However, the tile description on Pivnet shows that PAS 2.4 and 2.5 are also supported. So, either this document or PivNet description need to be changed.

**Comment by ljarzynski** [comment]
Thanks @parth-pandit ! I've just merged @heidmotron 's pull request. These version numbers should be updated on our site shortly.
