### ISSUE TITLE
cf delete-job-schedule syntax is wrong in documentation

### ISSUE THREAD

**Issue by cjcud** [pivotal-cf/docs-scheduler#22]
On https://docs.pivotal.io/pcf-scheduler/1-2/using-jobs.html#list-jobs, it indicates the syntax is 

>  cf delete-job-schedule SCHEDULE-GUID

However, when running the plugin, the following usage message is returned:

>Incorrect Usage: the required arguments are `JOB_NAME` and `SCHEDULE_GUID`
> 
> NAME:
>   delete-job-schedule - deletes a schedule for a job
>
> USAGE:
>   delete-job-schedule JOB_NAME SCHEDULE_GUID [--force]
>
> OPTIONS:
>   --force, -f   Force deletion without confirmation

Documentation should reflect all parameters... i.e.:

>  cf delete-job-schedule JOB-NAME SCHEDULE-GUID

**Comment by mlimonczenko** [comment]
Hello @cjcud,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
