### ISSUE TITLE
no mention in docs that scheduled tasks should be idempotent

### ISSUE THREAD

**Issue by beckettsean** [pivotal-cf/docs-scheduler#29]
It's not a requirement that scheduled jobs be idempotent, but it's a really really really good idea. The product all but assumes that the resolution of a failed job is just to run the job again later. There are few if any tools for pausing or ad hoc execution of scheduled jobs for that reason. Some customers are using scheduler with non-idempotent tasks and finding it challenging. Perhaps we can warn off those use cases earlier, or at least make them aware they are not using it in the best possible way.

**Comment by mlimonczenko** [comment]
Hello @beckettsean,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
