### ISSUE TITLE
Management of Time during DAY LIGHT SAVINGS

### ISSUE THREAD

**Issue by Sid4jbl** [pivotal-cf/docs-scheduler#30]
How this PCF Job scheduler handles Job during daylight Saving . For Example - I am running a job Every Sunday at **5PM EST** . Will the job start at **4PM EST** during Daylight Savings, or it will be starting at 5 PM only?

**Comment by ljarzynski** [comment]
Thanks @Sid4jbl for raising this issue. 
@heidmotron Is this something you could help clarify?

**Comment by KeepAustinWired** [comment]
Hi @Sid4jbl , 

Scheduler runs all tasks in UTC, and as such has no concept of Daylight Saving Time. 

Hope this helps.

**Comment by ljarzynski** [comment]
Thanks, @KeepAustinWired, closing out this issue. 
But Feel free to reopen, Siddhartha, if you feel additional clarification is needed.
