### ISSUE TITLE
Quartz Cron: conflicting starting day of week

### ISSUE THREAD

**Issue by fkeglevich** [pivotal-cf/docs-scheduler#46]
Docs says "Day of week starts at 0 for Sunday".
However when I tried to run a job earlier today (Wednesday) I needed to use 4 instead of 3:
`25 16 ? * 4`
So, it seems that the docs are wrong regarding the starting of the week, or that some information is missing.

Also, I believe the example "Every week at 6pm on Friday:" should be
`cf schedule-call my-call "0 18 ? * 6"`

It would be really nice to have a table with the corresponding weekdays and their numbers/abbreviations.
Also, the scheduling use UTC dates, however I found difficult to find this info on the docs.

**Comment by mlimonczenko** [comment]
Hello @fkeglevich,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
