### ISSUE TITLE
Add memory and disk limit details to docs

### ISSUE THREAD

**Issue by bbodenmiller** [pivotal-cf/docs-scheduler#55]
Supposedly can set memory and disk limit as of [1.3 CLI](https://docs.pivotal.io/scheduler/1-3/release-notes.html). Should update docs accordingly.

**Comment by mlimonczenko** [comment]
Hello @bbodenmiller,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
