### ISSUE TITLE
Make a branch for 1.5

### ISSUE THREAD

**Issue by Benjamintf1** [pivotal-cf/docs-scheduler#56]
Hello, We're working on releasing a 1.5 version of p-scheduler. We need a 1.5 branch of scheduler to create docs for this release. 

Thanks,

ben fuller

(link to story, not sure how helpful it will be though https://www.pivotaltracker.com/story/show/175841098)

**Comment by seviet** [comment]
Branch is here https://github.com/pivotal-cf/docs-scheduler/tree/1.5
