### ISSUE TITLE
link to HTTP API doc leads to 404

### ISSUE THREAD

**Issue by dbu** [pivotal-cf/docs-scheduler#6]
on the page http://docs.pivotal.io/pcf-scheduler/1-1/using-api.html there is a link to https://docs.pivotal.io/pcf-scheduler/api . that target does not work. looking at the url schema, i guessed to look at https://docs.pivotal.io/pcf-scheduler/1-1/api/ which seems to be the correct thing.

**Comment by animatedmax** [comment]
Thank you, @dbu This link should now be working correctly.

**Comment by dbu** [comment]
ah, and you deleted http://docs.pivotal.io/pcf-scheduler/1-1/using-api.html - got me confused a bit but makes totally sense. thanks for the fix, great that you keep the documentation up to date!
