### ISSUE TITLE
Scheduler HTTP API link is dead

### ISSUE THREAD

**Issue by grtessman** [pivotal-cf/docs-scheduler#61]
From this URL https://docs.pivotal.io/scheduler/1-5/using.html  - the  "Scheduler API Documentation" link is dead here. And this URL https://docs.pivotal.io/scheduler/1-5/ - the "Scheduler HTTP API" link is dead here. 
Would like to know how to use the Scheduler HTTP API but not finding anything helpful with dead links everywhere.

**Comment by seviet** [comment]
thanks for reporting @grtessman -- the docs app was misconfigured. this should be fixed now. https://docs.pivotal.io/scheduler/1-5/api/
